# https://taskfile.dev
version: "3"
tasks:
  default:
    deps:
      - build
    cmds:
      - bin/ecli

  sh: iex -S mix
  # elixir -S mix run --no-halt --detached
  # put into local paths
  build: mix escript.build --force
